### ISSUE TITLE
App for 2012 E-Series Test Install Error 

### ISSUE THREAD

**Issue by jimwilde** [Samsung/cordova-plugin-toast#14]
I've got a 2012 E-Series Samsung tv and wanted to try building an app for it as I came across this plugin.  I've put together an app and everything emulates in the browser.  Having perfomed the build/package step, I then went to install the app on my tv.

The smarthub is connecting and picking up the widgetlist.xml, starting the download of my app.  After a few seconds I get this message:
**Failed to install.  For more information, visit http://www.samsungdforum.com/Support/TVAppsSecurity.**

That page doesn't exist.

Here's my widgetlist.xml
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rsp stat="ok">
    <list>
        <widget id="****">
            <title>****</title>
            <type>user</type>
            <compression size="728" type="zip"/>
            <description/>
            <download>http://***.***.*.*/******.zip</download>
        </widget>
    </list>
</rsp>`

I didn't know what to put in the compression size field, so that is the zip file size in kb.

I can connect to the same place with a separate laptop and both view the xml file and access the zip, so I know that's not the problem.  My apache log isn't showing any messages or errors.

I'm running os x mavericks, building the app with phpStorm and using mamp to run the apache server.

Any help would be greatly appreciated.  Cheers.

**Comment by prozanne** [comment]
Hi :D
Sorry for late reply.
Please note that TOAST are not yet supported 12' Samsung TV, but It seems not related with your above issue.
This issue seems your application is not able to be installed at your TV. Unfortunately It doesn't seem to be TOAST own issue. You need to ask and report again about this issue at SDF. (Samsung Developer Forum http://www.samsungdforum.com/)
If you have any more question, please leave comment.

**Comment by jimwilde** [comment]
Thanks for your reply.  OK, not to worry.  I'm going to leave it for now.
