### ISSUE TITLE
app zip caching

### ISSUE THREAD

**Issue by bstegman** [Samsung/cordova-plugin-toast#26]
I'm not sure if this is a toast issue but I have a 2014 UN55H6203AF TV and it keeps caching my app zip file.  I end up having to unplug my tv and then re-sync to get the tv to accept the new app.

any thoughts?

**Comment by yongjuYoon** [comment]
Hello, bstegman.

I'm sorry but i can't understand the question.

what is the meaning of "app zip caching" & " ~ keeps caching my app zip file. ~" ?

plz explain more specifically.

Thank you.

**Comment by bstegman** [comment]
When I prepare/build my app and then I deploy it to the TV it does not get updated on the TV.  The TV keeps using the previous built app.  Even if I manually delete it from the TV then re-sync it keeps using the previously built app.

Your help is appreciated.  Let me know if you need more.

**Comment by yongjuYoon** [comment]
Hi, bstegman

Thank you for your explanation. I got it your problem.

In conclusion, "14 device" for faster loading any application is saving in cache memory its source code.
So that issue happened.

There are few solution :
 - instead of synch apps, try to launch apps from USB, and before, every time delete an application.
 ...
 ...

If you want more details, plz go to under Link.
[Link](https://www.samsungdforum.com/SamsungDForum/ForumView/df3455b529adf7c4?forumID=0ae7d999238ebef9)

Thank you.

**Comment by bstegman** [comment]
I will try that.  thanks.
