### ISSUE TITLE
cordova_plugin.js missing for webos 3.0 app

### ISSUE THREAD

**Issue by ireneng** [Samsung/cordova-plugin-toast#27]
Hi there,

I have built a simple player app using the toast api to play a smoothstream.
The app works great when I package and test for tizen. I am attempting to build the same player for webos.
When I run the webos app in debug mode, I get this error:
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///media/developer/apps/usr/palm/applications/com.yourdomain.app/cordova_plugins.js

I've checked my project files and the cordova_plugins.js is indeed missing. Where can I get this missing file or is there a way to workaround the issue. Any help is much appreciated.

Thanks!

**Comment by bstegman** [comment]
I am seeing the same thing

**Comment by yongjuYoon** [comment]
The error as you told is not a critical issue for running app.

I guess there are some other reason for smoothstream, but i can not check now because no your code.

So plz let me know your detailed test environment.
(webos version, toast version and so on)

if it is possible, give to me your project.

Thank you.

**Comment by ireneng** [comment]
@yongjuYoon 
Appreciate the reply! So it sounds like my app should technically work without the cordova_plugins.js. I'm fairly new at building a webos app so unsure what I"m missing to get playback to work with webos 3.0 using toast. 

My test environment:
LG webos tv emulator 3.0 - Oracle VM Virtual Box
Cordova plugin TOAST version 1.2.0
windows 10

I'm using a the following test stream (non-drm)
http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest

I've attached a console log from my app. You will see the internal logs from the toast plugin. Anything prefixed with [  LivApp ] are my custom logs.

![cordova_plugin_logs](https://cloud.githubusercontent.com/assets/14875192/21055352/15bb5cb4-bdff-11e6-872a-498fcf976059.JPG)

Thanks!

**Comment by yongjuYoon** [comment]
Hi,

Your problem seems to be related to "**webos tv emulator**". It is not supported in lg emulator. 

Also **Smooth Streaming is not recommended on webOS**.

For details :
[Features for webos](http://developer.lge.com/webOSTV/discover/specifications/webos-tv-platform/supported-media-formats/)
[Features for tizen](http://developer.samsung.com/tv/develop/specification/general-features)

It will be no problem if you use real TV.

Thank you.

**Comment by ireneng** [comment]
Hi @yongjuYoon,
I tested my app on a tv but the smooth stream still did not play.
However, when I test with a mp4 and HLS stream, they both played back fine on the tv.
On the webos documentation, I see that playready drm is listed which implies that smoothstream should be the streaming format.
I also ran the sample toast media app. The sample app also works with a mp4 and HLS stream but not smooth stream.
Any ideas?

Thanks!

**Comment by darangkim** [comment]
Hello,

WebOS does not recommend to use Smooth Streaming.
So, WebOS does not provide any guidelines. ([WebOS SmoothStreaming FAQ](http://developer.lge.com/webOSTV/common-page/faqs/faq-2822))
We can not support Smooth Streaming for WebOS.

You can contact the LGE person. ([WebOS QnA](http://developer.lge.com/community/forums/RetrieveForumContent.dev?detailContsId=FC21023052))
If you receive the guide by LGE, you need to realize by platform with this [guide](https://github.com/Samsung/cordova-plugin-toast/wiki/How-to-detect-platform).
