### ISSUE TITLE
Where should the Tizen SDK and WebOS SDK folder be located?

### ISSUE THREAD

**Issue by salihyasinseker** [Samsung/cordova-plugin-toast#28]
Hello. I get some errors when installing.

I have "Error loading cordova-browser" and "toast.js not found" errors.

I tried both step by step and shell setup.

Thanks.

![screen shot 2016-12-13 at 13 54 09](https://cloud.githubusercontent.com/assets/5829443/21137688/4afd3ece-c133-11e6-9695-42d8fc02066f.jpg)

![screen shot 2016-12-13 at 13 54 16](https://cloud.githubusercontent.com/assets/5829443/21137689/4afd60d4-c133-11e6-95b6-abacd141a9e9.jpg)

**Comment by yongjuYoon** [comment]
Hello, salihyasinseker

"Error loading cordova-browser" message is just a misleading error message.

That issue happen after upgrading cordova to 6.4.0, and the issue was reported and fixed.
(For details, https://issues.apache.org/jira/browse/CB-12088)

So you should downgrade to the 6.3.1, it will help you.


"The command '**tizen**' failed / The command '**ares**' failed" issue is related to
environment variables setting(Path). plz check again.
(For details, https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build#how-to-build-and-package)
