### ISSUE TITLE
deleteJS

### ISSUE THREAD

**Issue by bstegman** [Samsung/cordova-plugin-toast#31]
what is the best way to handle samsung's requirement to remove application data when the app is uninstalled?  I added the tag to config.xml but it isn't being bundled when I run the toast prepare or build commands.

"Deleting common files on the application uninstall"
http://developer.samsung.com/tv/develop/legacy-platform-library/tec00111/index#Deleting-common-files-on-the-application-uninstall

**Comment by pwsses** [comment]
deleteJS tag supported on Legacy Platform(a.k.a Orsay platform) 
If you want using other elements to a particular platform (ex. deleteJS elements), please refer 
"wiki > Create Project > How to add other elements..."(https://github.com/Samsung/cordova-plugin-toast/wiki/Create-Project)

Additionally, I will recommend using web storage, if your data size is under 5MB
Because web storage data is remove when the app is uninstalled.

**Comment by bstegman** [comment]
I am using web storage but my app for Samsung got rejected because I'm not using deletejs so I assumed I needed to cleanup web storage in deletejs.  If what your saying is true why are they rejecting my app because of it?

I'm really quit frustrated with the Samsung TV app store.  This same code base has been approved and running on the amazon fire stick for months now but it has become a nightmare getting it approved for the Samsung store.

thanks for your help.

**Comment by pwsses** [comment]
As I know, deleteJS is not mandatory element when you submit your Application in seller office.
So, you need check again for the reason of reject on your application.
please contact to samsung seller support menu.

**Comment by bstegman** [comment]
I am being told that when the app is removed and added back the user data is still there.  Based on what your saying this must be a problem with the Samsung TV not removing the localStorage which is where I store my data.

Thanks.

**Comment by bstegman** [comment]
I was looking through your closed issues and found this.  

https://github.com/Samsung/cordova-plugin-toast/issues/8

**Comment by pwsses** [comment]
webStorage(localStorage) data is remove when the app is uninstalled 
Because data is located under your application folder by tizen system.
If user data is still there when Application uninstall and reinstall. 
It is tizen tv issue. please contact to Samsung developer site(http://developer.samsung.com/forum/en)

**Comment by bstegman** [comment]
This is for Orsay.  Thanks for you help.

**Comment by pwsses** [comment]
Orsay TV also support web storage since 2014. If your Application service before 2014 than you should use the file system and deleteJS. As before my answer...
"deleteJS tag supported on Legacy Platform(a.k.a Orsay platform)
If you want using other elements to a particular platform (ex. deleteJS elements), please refer
"wiki > Create Project > How to add other elements..."(https://github.com/Samsung/cordova-plugin-toast/wiki/Create-Project)"

Actually, deleteJS is not mandatory element when you submit your Application in seller office.
So, you need check again for the reason of reject on your application.

**Comment by bstegman** [comment]
Yes, it is 2014.  I have followed up with them based on your comments.  By the way I think you guys have done a great job with toast.  Are you expecting to get android going soon?  It was mentioned on your previous sites but I don't see any mention of it anymore.

Thanks again for your feedback.

**Comment by pwsses** [comment]
Thanks for your interest on TOAST Project. 
As you know, We will have extend TOAST project to android TV Platform. 
But I don't have the detailed schedule. It will probably be released around May.
If you have any Idea, Join our project and make pull requests.

Thank you and Happy New Year!
