### ISSUE TITLE
Info key is not working (issued by. Simona)

### ISSUE THREAD

**Issue by prozanne** [Samsung/cordova-plugin-toast#38]
Please refer below sample application.
It uses Info key on sectv-orsay.

[TVInputDeviceSample.zip](https://github.com/Samsung/cordova-plugin-toast/files/791780/TVInputDeviceSample.zip)

**Comment by Belsim77** [comment]
Hi, 
thanks for reply.
Now on TIZEN "Info" key works!! :) but on ORSAY still not works.
The app exit when pressing "Info" key and also , MediaPlay, MediaPause, MediaRewind, MediaFastForward don't work (TV message displayed is "not available").

This code embedded in our app doesn't work:

toast.inputdevice.getSupportedKeys(function (keys) {
            for(var i=0, len=keys.length; i<len; i++) {
                keyList[keys[i].name] = keys[i].code;
                appLog('key/Code : '+ keys[i].name + " / " +keys[i].code);
                toast.inputdevice.registerKey(keys[i].name, function () {});
            }
        });

Is it possible for you to send us a sample with "Info" Key implemented in document.addEventListener("keydown", function (e) {} ?? 

TNX a lot
Regards
Simona

**Comment by yongjuYoon** [comment]
Hi, Belsim77

Please check the variable declaration once again.

In JS, For using a variable as an "object", you have to declare a variable as an "object".

For example,
`var keyList= {};` OR `var keyList= new Array();`
`keyList[keys[i].name] = keys[i].code;`

If you gotta same problem, send to our team your "full code" about key setting in order to help you.

There is no way in which I can know any more in the current situation....

Thank you.

**Comment by Belsim77** [comment]
Hi, yongjuYoon

thank you so much for your help, we solved.

We were able to integrate  TOAST and AngularJs!!!

thank you
Simona
