### ISSUE TITLE
Media inputDevice

### ISSUE THREAD

**Issue by guipdutra** [Samsung/cordova-plugin-toast#39]
Hello, I'm trying to mapping the keys around the media(MediaPlayPause, MediaStop, MediaPlay, ... )

But I noticed that in Orsay(tvKeyCode.MediaPlay) and Tizen(tvKeyCode.KEY_PLAY) the keys are different. There is any abstraction from toast for this difference be transparent for me and I do not have to use "If this platform use this key".

**Comment by yongjuYoon** [comment]
Hello, @guipdutra 

We expect, you may be trying to mapping the keys  by using "TizenKeyValue.js"

But from now on, you do not need to be so, because we provide that in TOAST.

If you check the [media sample app](https://github.com/Samsung/cordova-plugin-toast/tree/master/sample/media) OR [drmmedia sample app](https://github.com/Samsung/cordova-plugin-toast/tree/master/sample/drmmedia), you can get the answer which you want.

Thank you.

**Comment by guipdutra** [comment]
Hello, @yongjuYoon 

Thank you for you answer.

Using the same code in the example works perfeclty in Orsay and webOS. But in Tizen did not work, because the key of MediaPlay in Tizen is KEY_PLAY and do not get mapped.

My question is should I put the KEY_PLAY in usedKeys variable?

```js
var usedKeys = [
        'MediaPause',
        'MediaPlay',
        'MediaFastForward',
        'MediaRewind',
        'MediaStop'
        'KEY_PLAY'
    ];
````

**Comment by yongjuYoon** [comment]
Hi,

The keycode of `KEY_PLAY` in 'TizenTVKeyValue.js' is 415.

It means that `MediaPlay` and `KEY_PLAY` is the same meaning.
And in TOAST, we provide this role as the mediaplay key.

So you can use the `MediaPlay` key in place of  `KEY_PLAY`.

Also you can check the value of 'KEY_PLAY' in TizenTVKeyValue.js' at the [SDsite](http://developer.samsung.com/tv/develop/tutorials/how-to-convert-app/converting-smart-tv-app-to-tizen-tv-app#app-converting-guide-1-10)

Thank you.

**Comment by richardman1** [comment]
Hello,

I do have to agree that the way the apps are now, are not working on Tizen. I have followed your guidelines for the media sample app and they are working immediately on webOS and Orsay, but not on Tizen.
