### ISSUE TITLE
Black screen after switching between apps on Samsung TV

### ISSUE THREAD

**Issue by lucasromanojf** [Samsung/cordova-plugin-toast#50]
Hi,

my Samsung app failed on testing because the video plays normally but when user switch to another app and then switch back, the video stops playing and player area becomes black (black screen).

Is this an issue or is there anything I have do to solve this?

Thanks!

**Comment by prozanne** [comment]
Hi there :D

It seems you are in trouble with playing video on multitasking scenario.
Could you please refer below samsung developer site?
http://developer.samsung.com/tv/develop/guides/fundamentals/multitasking
In TOAST, we are not support webapis,avplay.restore and webapis.avplay.suspend API which are related multitasking playing video API. So you need to add this api with detecting platform as refer below guide
https://github.com/Samsung/cordova-plugin-toast/wiki/How-to-detect-platform
-------------------------------------------------------------------------------
I think this issue seems not related with TOAST.
You can get more help like this case in the samsung developer site.
http://developer.samsung.com/tv/develop

**Comment by lucasromanojf** [comment]
Hi!

Using media.pause() when document hidden and media.play() on resume seems to solve the issue.

Thanks!
