### ISSUE TITLE
Can't get Ajax calls to work on TV Device

### ISSUE THREAD

**Issue by jandante** [Samsung/cordova-plugin-toast#62]
Hi,
This might not be the beste place, but I can't find help on the forum.

I'm trying to create an app for Samsung LFD screens. I got a working app via toast in the emulator but on the TV device itself my Ajax calls are not working...

Here is the link to the forum with some more information and some actions i tried: http://developer.samsung.com/forum/thread/ajax-calls-in-tizen-app/201/320787?boardName=SDK&startId=zzzzz~

Maybe someone here knows something.

Thanks in advance for checking this out.

**Comment by pwsses** [comment]
Hi 
please refer Tizen content Security Policy
url : https://developer.tizen.org/development/training/web-application/understanding-tizen-programming/web-runtime

Tizen supported CSP and WARP, you choose one of them in config.xml

CSP tag : 
<tizen:content-security-policy>default-src *; script-src *; connect-src *; img-src *; style-src *;</tizen:content-security-policy>

WARP tag : 
<access origin="*" subdomains="true"/>

In your case(accroding to url), Both are in use. 
If you don't need high Class Security, I recommend using WARP because it is simple and easy.

thanks

**Comment by jandante** [comment]
thanks for you help. I tried it, but didn't working. More over when I delete the CSP tag the javascript isn't even working anymore on the device. It is on the emulator. Do you have an example config.xml that could serve as a starting point for beginners?

**Comment by prozanne** [comment]
Hi :D
Unfortunately It is not much related with TOAST project, so we can't help you properly.
Can you check b2b samsung forum, If you makes LFD application?
I don't know exactly but you might find the answer there.
Because I know that many b2b developers refer this site for making their application.

https://www.samsungdforum.com/b2b
